package blanco.restgeneratorkt;

import blanco.cg.BlancoCgObjectFactory;
import blanco.cg.valueobject.*;

import java.io.File;
import java.util.List;

/**
 * RequestDeserializer クラスを生成するためのクラスです。
 */
public class BlancoRestGeneratorKtRequestDeserializerClass {
    /**
     * このクラス自身のクラス名
     */
    public static final String CLASS_NAME = "BlancoRestGeneratorKtRequestDeserializer";

    /**
     * blancoCg オブジェクトファクトリ。
     */
    private BlancoCgObjectFactory fCgFactory = null;

    /**
     * このクラスが含まれるソースコード。
     */
    private BlancoCgSourceFile fCgSourceFile = null;

    private String fRuntimepackage = null;

    public BlancoRestGeneratorKtRequestDeserializerClass(
            final BlancoCgObjectFactory argCgFactory,
            final String argRuntimepackage,
            final String argEncodeing,
            final int argTab
    ) {
        fCgFactory = argCgFactory;
        fRuntimepackage = argRuntimepackage;
        fCgSourceFile = fCgFactory.createSourceFile(argRuntimepackage + ".util",
                "This code is generated by blanco Framework.");
        fCgSourceFile.setEncoding(argEncodeing);
        fCgSourceFile.setTabs(argTab);
    }

    public BlancoCgSourceFile expand() {
        final BlancoCgClass cgClass = fCgFactory.createClass(CLASS_NAME, null);
        fCgSourceFile.getClassList().add(cgClass);

        cgClass.setFinal(true);
        cgClass.setAccess("");
        cgClass.setGenerics("S : RequestHeader, T : ApiTelegram"); // <> は自動でつけられる
        BlancoCgType stdDeserializer = fCgFactory.createType(
                "com.fasterxml.jackson.databind.deser.std.StdDeserializer"
        );
        cgClass.getExtendClassList().add(stdDeserializer);
        stdDeserializer.setGenerics("CommonRequest<S, T>");
        stdDeserializer.setConstructorArgs("vc");

        {
            // Description
            final List<String> listDesc = cgClass.getLangDoc()
                    .getDescriptionList();

            listDesc.add("blancoRestGeneratorが共通的に利用するユーティリティクラス。");
            listDesc.add("");
            listDesc.add("このクラスはblancoRestGeneratorが生成したソースコードで利用されます <br>");
            listDesc
                    .add("このクラスは blancoRestGeneratorが生成したソースコードから利用されます。直接呼び出すことは推奨されません。");
            listDesc.add("");
            listDesc.add("@since 2020.09.01");
            listDesc.add("@author blanco Framework");
        }


        {
            // import
            // 電文は runtimepackage + ".valueobject" に存在する前提
            fCgSourceFile.getImportList().add(fRuntimepackage + ".valueobject.ApiTelegram");
            fCgSourceFile.getImportList().add(fRuntimepackage + ".valueobject.CommonRequest");
            fCgSourceFile.getImportList().add(fRuntimepackage + ".valueobject.RequestHeader");
            // Jackson
            fCgSourceFile.getImportList().add("com.fasterxml.jackson.core.JsonParser");
            fCgSourceFile.getImportList().add("com.fasterxml.jackson.databind.DeserializationContext");
            fCgSourceFile.getImportList().add("com.fasterxml.jackson.databind.JsonNode");
            fCgSourceFile.getImportList().add("com.fasterxml.jackson.databind.ObjectMapper");
            fCgSourceFile.getImportList().add("com.fasterxml.jackson.databind.deser.std.StdDeserializer");
        }

        {
            // fields
            BlancoCgField vc = fCgFactory.createField("vc", "java.lang.Class", null);
            cgClass.getConstructorArgList().add(vc);
            vc.getType().setGenerics("*"); // <> は自動的につけられる
            vc.setConst(true); // val

            BlancoCgField infoClazz = fCgFactory.createField("infoClazz", "java.lang.Class", "CommonRequest#info の実装クラスを設定します。");
            cgClass.getFieldList().add(infoClazz);
            infoClazz.getType().setGenerics("S");
            infoClazz.setConst(false); // var
            infoClazz.setAccess("");
            infoClazz.setFinal(true);
            infoClazz.setNotnull(false); // nullable
            infoClazz.setDefault("null");

            BlancoCgField telegramClazz = fCgFactory.createField("telegramClazz", "java.lang.Class", "CommonRequest#telegram の実装クラスを設定します。");
            cgClass.getFieldList().add(telegramClazz);
            telegramClazz.getType().setGenerics("T");
            telegramClazz.setConst(false); // var
            telegramClazz.setAccess("");
            telegramClazz.setFinal(true);
            telegramClazz.setNotnull(false); // nullable
            telegramClazz.setDefault("null");
        }

        {
            // methods
            cgClass.getMethodList().add(buildDeserializeMethod());
            cgClass.getMethodList().add(buildParseRequestHeader());
            cgClass.getMethodList().add(buildParseTelegram());
        }

        return fCgSourceFile;
    }

    private BlancoCgMethod buildDeserializeMethod() {
        BlancoCgMethod deserialize = fCgFactory.createMethod("deserialize", "deserialize JSON content into the value type this serializer handles");
        deserialize.setOverride(true);
        deserialize.setFinal(true);

        BlancoCgParameter jp = fCgFactory.createParameter("jp", "com.fasterxml.jackson.core.JsonParser", "JsonParseクラスを受け取ります");
        deserialize.getParameterList().add(jp);
        jp.setNotnull(false);

        BlancoCgParameter ctxt = fCgFactory.createParameter("ctxt", "com.fasterxml.jackson.databind.DeserializationContext", "DeserializationContextを受け取ります");
        deserialize.getParameterList().add(ctxt);
        ctxt.setNotnull(false);

        BlancoCgReturn cgReturn = fCgFactory.createReturn(fRuntimepackage + ".valueobject.CommonRequest", "JSONをparseし、CommonRequestに詰めて返します。");
        deserialize.setReturn(cgReturn);
        cgReturn.getType().setGenerics("S, T");
        cgReturn.setNullable(true);

        // method の本体
        List<String> lineList = deserialize.getLineList();

        lineList.add("");
        lineList.add("val node = jp?.codec?.readTree<JsonNode>(jp)");
        lineList.add("var info: S? = null");
        lineList.add("var telegram: T? = null");
        lineList.add("val fieldIte = node?.fields()");
        lineList.add("");

        lineList.add("while(fieldIte != null && fieldIte.hasNext()){");
        lineList.add("val fieldEntry = fieldIte.next()");
        lineList.add("val value = fieldEntry.value");
        lineList.add("if(value != null){");
        lineList.add("if(\"info\".equals(fieldEntry.key, true)){");
        lineList.add("info = this.parseRequestHeader(value)");
        lineList.add("} else if (\"telegram\".equals(fieldEntry.key, true)){");
        lineList.add("telegram = this.parseTelegram(value)");
        lineList.add("}");
        lineList.add("}");
        lineList.add("}");

        lineList.add("");

        lineList.add("var retval: CommonRequest<S, T>? = null");
        lineList.add("if (info != null) {");
        lineList.add("retval = CommonRequest<S, T>(info, telegram)");
        lineList.add("}");

        lineList.add("");

        lineList.add("return retval");

        return deserialize;
    }

    private BlancoCgMethod buildParseRequestHeader() {
        BlancoCgMethod parser = fCgFactory.createMethod("parseRequestHeader", "RequestHeaderをparseします");
        parser.setOverride(false);
        parser.setFinal(true);
        parser.setAccess("private");

        BlancoCgParameter node = fCgFactory.createParameter("node", "com.fasterxml.jackson.databind.JsonNode", "JsonNodeクラスを受け取ります");
        parser.getParameterList().add(node);
        node.setNotnull(true);

        BlancoCgReturn cgReturn = fCgFactory.createReturn("S", "JSONをparseし、S に詰めて返します。");
        parser.setReturn(cgReturn);
        cgReturn.setNullable(false);

        // method の本体
        List<String> lineList = parser.getLineList();

        lineList.add("val mapper = ObjectMapper()");
        lineList.add("val header = mapper.convertValue<S>(node, infoClazz)");
        lineList.add("return header");

        return parser;
    }

    private BlancoCgMethod buildParseTelegram() {
        BlancoCgMethod parser = fCgFactory.createMethod("parseTelegram", "ApiTelegramをparseします");
        parser.setOverride(false);
        parser.setFinal(true);
        parser.setAccess("private");

        BlancoCgParameter node = fCgFactory.createParameter("node", "com.fasterxml.jackson.databind.JsonNode", "JsonNodeクラスを受け取ります");
        parser.getParameterList().add(node);
        node.setNotnull(true);

        BlancoCgReturn cgReturn = fCgFactory.createReturn("T", "JSONをparseし、T に詰めて返します。");
        parser.setReturn(cgReturn);
        cgReturn.setNullable(true);

        // method の本体
        List<String> lineList = parser.getLineList();

        lineList.add("val mapper = ObjectMapper()");
        lineList.add("val telegram = mapper.convertValue<T>(node, telegramClazz)");
        lineList.add("return telegram");

        return parser;
    }
}
